### PR TITLE
Use ssreflect's coding style in files.

### PR DESCRIPTION
**Pull request by ejgallego**
Hi, thanks for the library.

I was having a look to it and noticed that some code did not adhere to ssreflect coding guidelines, so I tweaked it a bit; it has the side effect of making some proofs shorter.

Doing a PR in case you are interested.

Best,
E.

### CODE REVIEW

**Comment by artart78** [comment]
Wow, thanks, I realized how inexperienced I am!

Could you please explicit the (\* XXX *)s you marked? I don't understand what's the "problem" here.

I'm also waiting for your answer on the other issue before merging.

Thanks for the work!

By the way, there are two 'admit's hanging around in the code (examples/queens.v & src/repr_op.v). They seem to be trivial but we failed to find a proper way to prove them —you might be able to help, and we'd be very grateful!

**Comment by ejgallego** [comment]
Hi @artart78 , you are welcome, thanks for putting the library online, it was really useful.

The XXX are related to a couple of thoughts I had while reading the libs; IMHO I prefer to send an email if you don't mind.

**Comment by artart78** [comment]
Sure! Feel free to send me an email at firstname.lastname@ens-lyon.org (my first & last name should appear in the commits)

**Comment by ejgallego** [comment]
Yeah, will do thanks! I'm sorry for the delay, I've been a bit busy as of late.

**Pull request merged**
